# Generated by Django 3.2.6 on 2021-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_of_refers',
            field=models.IntegerField(default=0),
        ),
    ]
