# Generated by Django 3.2.6 on 2021-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211008_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='links_created',
            field=models.IntegerField(default=0),
        ),
    ]
