# Generated by Django 3.2.4 on 2021-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
