# Generated by Django 3.2.4 on 2021-06-27 13:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
        ),
    ]
