# Generated by Django 3.2.6 on 2021-08-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referral_stored_in_wallet'),
        ('users', '0003_orphanlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanlist',
            name='referral_obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
    ]
