# Generated by Django 3.2.6 on 2021-10-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_links_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_refs',
            field=models.IntegerField(default=0),
        ),
    ]
