# Generated by Django 3.2.4 on 2021-06-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='Phone_Number',
        ),
    ]
