# Generated by Django 3.2.6 on 2021-08-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_orphanlist_referral_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wallet',
            new_name='orphan_cashback',
        ),
    ]
