# Generated by Django 3.2.6 on 2021-09-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210909_1649'),
        ('referrals', '0005_auto_20210909_1649'),
        ('users', '0007_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphanlist',
            old_name='orphan_cashback',
            new_name='referee_cashback',
        ),
        migrations.AddField(
            model_name='orphanlist',
            name='orderRef_obj',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.orderref'),
        ),
        migrations.AddField(
            model_name='orphanlist',
            name='refereeEmail',
            field=models.EmailField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='orphanlist',
            name='referral_obj',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
    ]
