# Generated by Django 3.2.6 on 2021-09-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210909_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrphanList',
        ),
    ]
