# Generated by Django 3.2.6 on 2021-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(verbose_name='Date Joined')),
                ('store_link', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Partner Merchants',
            },
        ),
        migrations.CreateModel(
            name='Zalora_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_link', models.CharField(default='None', max_length=500)),
                ('cashback_amt', models.IntegerField(default=0)),
                ('img_link', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Zalora Merchants',
            },
        ),
    ]
