# Generated by Django 3.2.6 on 2021-09-22 22:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_merchant',
            name='img_link',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='webhookOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_email', models.EmailField(default='None', max_length=60)),
                ('location', models.CharField(default='SG', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.partner_merchant')),
            ],
        ),
    ]
