# Generated by Django 3.2.6 on 2021-08-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='store_link',
            field=models.URLField(null=True),
        ),
    ]
