# Generated by Django 3.2.6 on 2021-10-01 20:59

from django.db import migrations, models
import merchants.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_partner_merchant_cashback_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookorders',
            name='products',
            field=models.JSONField(default=merchants.models.jsonfield_default_value, null=True),
        ),
    ]
