# Generated by Django 3.2.6 on 2021-08-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_store_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='store_link',
            field=models.URLField(),
        ),
    ]
