# Generated by Django 3.2.6 on 2021-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_store_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='store_image_link',
            field=models.URLField(null=True),
        ),
    ]
