# Generated by Django 3.2.6 on 2021-10-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_webhookorders_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zalora_Brand',
            new_name='Amazon_Brand',
        ),
        migrations.AlterModelOptions(
            name='amazon_brand',
            options={'verbose_name_plural': 'Amazon Merchants'},
        ),
    ]
