# Generated by Django 3.2.6 on 2021-08-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchant_store_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='store_image_link',
        ),
    ]
