# Generated by Django 3.2.6 on 2021-08-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_alter_merchant_store_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='store_link',
        ),
    ]
