# Generated by Django 3.2.6 on 2021-11-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_auto_20211008_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookorders',
            options={'verbose_name_plural': 'Webhook Orders'},
        ),
    ]
