# Generated by Django 3.2.6 on 2021-08-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_remove_merchant_store_image_link'),
        ('merchants', '0006_remove_merchant_store_link'),
    ]

    operations = [
    ]
