# Generated by Django 3.2.6 on 2021-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_merge_20210811_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='store_link',
            field=models.URLField(null=True),
        ),
    ]
