# Generated by Django 3.2.6 on 2021-08-16 05:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('referer_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('referee_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('receipt', models.ImageField(default='default.jpg', upload_to='receipts')),
                ('is_Verified', models.BooleanField(default=False)),
                ('is_Published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
