# Generated by Django 3.2.6 on 2021-09-11 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.IntegerField(default=0)),
                ('orderID', models.CharField(default=0, max_length=20)),
                ('totalAmt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('referer_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('referee_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('referee_email', models.EmailField(default='None', max_length=50)),
                ('referee_username', models.CharField(default='Not Signed Up', max_length=40)),
                ('is_Verified', models.BooleanField(default=False)),
                ('stored_in_wallet', models.BooleanField(default=False)),
                ('referee_has_account', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
                ('orderRef_obj', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderref')),
                ('referer_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrphanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refereeEmail', models.EmailField(default=0, max_length=40)),
                ('referee_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('referral_obj', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral')),
            ],
        ),
    ]
