# Generated by Django 3.2.6 on 2021-10-01 21:02

from django.db import migrations, models
import referrals.models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='products',
            field=models.JSONField(default=referrals.models.jsonfield_default_value, null=True),
        ),
    ]
