# Generated by Django 3.2.4 on 2021-06-27 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referral_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
