# Generated by Django 3.2.6 on 2021-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_referee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='stored_in_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
