# Generated by Django 3.2.4 on 2021-06-27 14:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referral_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referee',
        ),
        migrations.AddField(
            model_name='referral',
            name='referee_Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
