# Generated by Django 3.2.6 on 2021-10-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0003_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='orphanReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('referral_obj', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.receipts')),
            ],
        ),
    ]
