# Generated by Django 3.2.6 on 2021-09-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('referrals', '0003_referral_stored_in_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
    ]
