# Generated by Django 3.2.6 on 2021-09-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_alter_referral_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referer',
            new_name='referer_username',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='is_Published',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referee_Phone_Number',
        ),
        migrations.AddField(
            model_name='referral',
            name='orderID',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='sessionID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='totalAmt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
