# Generated by Django 3.2.6 on 2021-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_orphanreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='referee',
            field=models.CharField(default='None', max_length=150, null=True),
        ),
    ]
