# Generated by Django 3.2.4 on 2021-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20210627_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_Published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
