# Generated by Django 3.2.6 on 2021-08-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210811_1247'),
        ('referrals', '0005_auto_20210630_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referer', to='users.money_user'),
        ),
    ]
