# Generated by Django 3.2.6 on 2021-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_auto_20210909_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referee_email',
            field=models.EmailField(default='None', max_length=20),
        ),
    ]
