# Generated by Django 3.2.6 on 2021-08-11 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0006_alter_referral_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referer', to=settings.AUTH_USER_MODEL),
        ),
    ]
