# Generated by Django 3.2.6 on 2021-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_receipts_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
