# Generated by Django 3.2.6 on 2021-09-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_webhookorder_ref_obj'),
        ('referrals', '0007_alter_referral_referee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referee_has_account',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrphanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refereeEmail', models.EmailField(default=0, max_length=40)),
                ('referee_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('orderRef_obj', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.orderref')),
                ('referral_obj', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral')),
            ],
        ),
    ]
