# Generated by Django 3.2.6 on 2021-10-08 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_receipts_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
