# Generated by Django 3.2.6 on 2021-10-09 18:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_receipts_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='referee_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
