# Generated by Django 3.2.6 on 2021-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_alter_receipts_referee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanreceipt',
            name='referee',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
