# Generated by Django 3.2.6 on 2021-09-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_alter_referral_referer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanlist',
            name='referral_obj',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
    ]
