# Generated by Django 3.2.6 on 2021-09-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210909_1827'),
        ('referrals', '0010_alter_orphanlist_referral_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanlist',
            name='orderRef_obj',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderref'),
        ),
    ]
