# Generated by Django 3.2.6 on 2021-11-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0010_orphanreceipt_referee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'verbose_name_plural': 'Uploaded Receipts'},
        ),
    ]
