# Generated by Django 3.2.6 on 2021-09-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0011_alter_orphanlist_orderref_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referer_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
