# Generated by Django 3.2.6 on 2021-11-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_alter_webhookorders_options'),
        ('referrals', '0011_alter_receipts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='webhook',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.webhookorders'),
        ),
    ]
