# Generated by Django 3.2.6 on 2021-09-10 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0012_alter_referral_referer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referer_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer', to=settings.AUTH_USER_MODEL),
        ),
    ]
