# Generated by Django 3.2.6 on 2021-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0015_alter_referral_referee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referee_username',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
