# Generated by Django 3.2.6 on 2021-09-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0017_alter_referral_referee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referee_username',
            field=models.CharField(default='Not Signed Up', max_length=40),
        ),
    ]
