# Generated by Django 3.2.6 on 2021-09-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210910_1417'),
        ('referrals', '0019_remove_orphanlist_orderref_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='orderRef_obj',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderref'),
        ),
    ]
