# Generated by Django 3.2.6 on 2021-08-25 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0003_referral_stored_in_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=12)),
                ('order_id', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('merchant_name', models.CharField(max_length=20)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ref_obj', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral')),
            ],
        ),
    ]
