# Generated by Django 3.2.6 on 2021-09-11 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=40)),
                ('discount_code', models.CharField(max_length=12)),
                ('order_id', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='orderRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.IntegerField()),
                ('orderID', models.CharField(max_length=20)),
                ('totalAmt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('refereeEmail', models.EmailField(default='None', max_length=40)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('merchant_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
                ('referrer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
