# Generated by Django 3.2.6 on 2021-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookorder',
            name='customer_email',
            field=models.EmailField(default='None', max_length=60),
        ),
        migrations.AddField(
            model_name='webhookorder',
            name='location',
            field=models.CharField(default='SG', max_length=20),
        ),
    ]
