# Generated by Django 3.2.6 on 2021-08-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referral_stored_in_wallet'),
        ('api', '0002_rename_webhook_orders_webhook_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webhook_Order',
            new_name='WebhookOrder',
        ),
    ]
