# Generated by Django 3.2.6 on 2021-09-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_webhook_order_webhookorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderRefLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=20)),
                ('sessionID', models.IntegerField()),
                ('orderID', models.CharField(max_length=20)),
                ('totalAmt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('refereeEmail', models.EmailField(max_length=40)),
                ('merchant_name', models.CharField(max_length=20)),
            ],
        ),
    ]
