# Generated by Django 3.2.6 on 2021-09-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_webhookorder_discount_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookOrder',
        ),
    ]
