# Generated by Django 3.2.6 on 2021-09-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_partner_merchant_cashback_amt'),
        ('api', '0004_delete_webhookorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderref',
            name='webhook_obj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.webhookorders'),
        ),
    ]
