# Generated by Django 3.2.6 on 2021-09-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderreflinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderRefLinks',
            new_name='orderRefs',
        ),
    ]
