# Generated by Django 3.2.6 on 2021-09-09 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_orderreflinks_orderrefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=20)),
                ('sessionID', models.IntegerField()),
                ('orderID', models.CharField(max_length=20)),
                ('totalAmt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('refereeEmail', models.EmailField(max_length=40)),
                ('merchant_name', models.CharField(max_length=20)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='orderRefs',
        ),
    ]
