# Generated by Django 3.2.6 on 2021-10-04 02:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_webhookorders_products'),
        ('api', '0005_orderref_webhook_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numClicks', models.IntegerField()),
                ('date_recorded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('merchant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.partner_merchant')),
            ],
        ),
    ]
