# Generated by Django 3.2.6 on 2021-10-27 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trackwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='involveAsia_PostbackURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('order_id', models.IntegerField()),
                ('conversion_id', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
