# Generated by Django 3.2.6 on 2021-11-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_auto_20211008_1418'),
        ('api', '0007_involveasia_postbackurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('matched', models.BooleanField(default=False)),
                ('orderRef_obj', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderref')),
                ('webhook', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.webhookorders')),
            ],
        ),
    ]
