# Generated by Django 3.2.6 on 2021-12-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_involveasia_postbackurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invalidorder',
            options={'verbose_name_plural': 'Invalid Referrals'},
        ),
        migrations.AlterModelOptions(
            name='involveasia_postbackurl',
            options={'verbose_name_plural': 'Involve Postback URLs'},
        ),
        migrations.AlterModelOptions(
            name='orderref',
            options={'verbose_name_plural': 'Referral Orders'},
        ),
    ]
