# Generated by Django 3.2.6 on 2021-11-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_controller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invalidorder',
            options={'verbose_name_plural': 'Invalid Referrals'},
        ),
        migrations.AlterModelOptions(
            name='involveasia_postbackurl',
            options={'verbose_name_plural': 'Involve Postback URLs'},
        ),
        migrations.AlterModelOptions(
            name='order_controller',
            options={'verbose_name_plural': 'Order Controller'},
        ),
        migrations.AlterModelOptions(
            name='orderref',
            options={'verbose_name_plural': 'Referral Orders'},
        ),
    ]
