# Generated by Django 3.2.6 on 2021-09-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('api', '0009_alter_orderref_merchant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderref',
            name='merchant_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
    ]
