# Generated by Django 3.2.6 on 2021-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_orderref_merchant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderref',
            name='merchant_name',
            field=models.CharField(max_length=20),
        ),
    ]
