# Generated by Django 3.2.6 on 2021-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderref_merchant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderref',
            name='referrer',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
