# Generated by Django 3.2.6 on 2021-09-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
        ('api', '0012_alter_orderref_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderref',
            name='merchant_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='orderref',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
