# Generated by Django 3.2.6 on 2021-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210909_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderref',
            name='merchant_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderref',
            name='refereeEmail',
            field=models.EmailField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='orderref',
            name='referrer',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
