# Generated by Django 3.2.6 on 2021-09-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210910_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderref',
            name='merchant_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='webhookorder',
            name='merchant_name',
            field=models.CharField(max_length=40),
        ),
    ]
